### ISSUE TITLE
Behaviour when insert line comment at the beginning of the line

### ISSUE THREAD

**Issue by acuarica** [acuarica/codemirror.next#1]
Example of the behaviour when line commenting at the beginning of the line:

![Untitled](https://user-images.githubusercontent.com/4592980/79227892-e5779100-7e60-11ea-8d00-c1786926db6d.gif)

**Comment by marijnh** [comment]
I think it is okay to leave this as it is until any actual users complain, at which point we can revisit it. Both behaviors seem reasonable.

**Comment by acuarica** [comment]
Perfect then.

Thanks.
